### ISSUE TITLE
Does not work on EdgeRouter

### ISSUE THREAD

**Issue by tyranian** [Twanislas/ubnt-cloudflared#1]
Hi this doesn't seem to work on edgerouter

I believe due to /usr/local/bin/ not existing as its just /local/bin

**Comment by Twanislas** [comment]
Hi !

Thanks for reporting !

I will try and move the binary location to /opt.
Would you mind checking if /opt is present on EdgeRouter as I don't have one handy right now ?

I'll check when I have time to give it a go ;)

Cheers !

**Comment by tyranian** [comment]
Hi,

/opt does exist. I manually got cloudflared running using your script as a guide and its running perfectly.

**Comment by Twanislas** [comment]
Wonderful, will update the code !
Thank you !
